import { StyleSheet } from 'react-native';
import { responsiveFontSize, scale } from '../constants/Responsive';

export const styles = StyleSheet.create({
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    marginTop: scale(28),
    marginBottom: 0,
  },
  headerIcon: {
    padding: scale(8),
  },
  profileCard: {
    backgroundColor: '#181818',
    borderRadius: scale(20),
    marginHorizontal: scale(16),
    padding: scale(20),
    alignItems: 'center',
  },
  avatarBig: {
    width: scale(90),
    height: scale(90),
    borderRadius: scale(45),
    backgroundColor: '#FFFF00', // bright yellow inside
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: scale(12),
    borderWidth: 2,
    borderColor: '#181818', // black border
  },
  avatarBigText: {
    color: '#181818',
    fontSize: responsiveFontSize(32),
    fontWeight: '400',
    letterSpacing: 0.5,
  },
  profileName: {
    color: '#FFFF00',
    fontSize: responsiveFontSize(18),
    fontWeight: '300',
    letterSpacing: 0.8,
  },
  profileFullName: {
    color: '#FFFF00',
    fontSize: responsiveFontSize(16),
    marginTop: scale(4),
    fontWeight: '300',
  },
  profileRole: {
    color: '#b0bec5',
    fontSize: responsiveFontSize(14),
    marginTop: scale(4),
    fontWeight: '300',
  },
  profileStatsRow: {
    flexDirection: 'row',
    marginTop: scale(16),
  },
  profileStat: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: scale(10),
  },
  profileStatText: {
    color: '#fff',
    marginLeft: scale(6),
    fontWeight: '300',
  },
  friendButton: {
    backgroundColor: '#FFFF00',
    paddingVertical: scale(10),
    paddingHorizontal: scale(20),
    borderRadius: scale(20),
    alignSelf: 'center',
    marginVertical: scale(15),
  },
  friendButtonText: {
    color: '#181818',
    fontSize: responsiveFontSize(14),
    fontWeight: '400',
    letterSpacing: 0.5,
  },
  sectionTitle: {
    color: '#FFFF00',
    fontSize: responsiveFontSize(17),
    fontWeight: '300',
    marginBottom: scale(10),
    letterSpacing: 0.8,
  },
  aboutText: {
    color: '#FFFF00',
    fontSize: responsiveFontSize(15),
    lineHeight: scale(22),
    fontWeight: '300',
  },
  sportSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFF00',
    borderRadius: scale(14),
    padding: scale(14),
    borderWidth: 2,
    borderColor: '#FFFF00',
  },
  sportDropdown: {
    position: 'absolute',
    top: scale(54),
    left: 0,
    right: 0,
    zIndex: 10,
    backgroundColor: '#FFFF00',
    borderRadius: scale(14),
    borderWidth: 2,
    borderColor: '#FFFF00',
    overflow: 'hidden',
  },
  sportItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: scale(12),
    paddingHorizontal: scale(10),
  },
  sportItemSelected: {
    backgroundColor: '#FFFF00',
  },
  sportItemText: {
    color: '#181818',
    fontSize: responsiveFontSize(14),
    fontWeight: '400',
    letterSpacing: 0.5,
  },
  sportSavingIndicator: {
    position: 'absolute',
    right: 50,
    top: 18,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginHorizontal: 16,
  },
  statCard: {
    backgroundColor: '#181818',
    borderRadius: scale(14),
    width: '48%',
    padding: scale(16),
    marginBottom: scale(12),
    alignItems: 'center',
  },
  statValue: {
    color: '#fff',
    fontSize: responsiveFontSize(24),
    fontWeight: 'bold',
    marginTop: scale(8),
  },
  statLabel: {
    color: '#b0bec5',
    fontSize: responsiveFontSize(14),
    marginTop: scale(4),
    textAlign: 'center',
    fontWeight: '300',
  },
  achievementsRow: {
    paddingHorizontal: scale(16),
  },
  achEmpty: {
    color: '#b0bec5',
    textAlign: 'center',
    marginTop: 10,
  },
  achCard: {
    backgroundColor: '#181818',
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    alignItems: 'center',
  },
  achTitle: {
    color: '#fff',
    fontSize: responsiveFontSize(16),
    fontWeight: 'bold',
    marginTop: scale(8),
  },
  achDesc: {
    color: '#b0bec5',
    fontSize: responsiveFontSize(14),
    textAlign: 'center',
    marginTop: scale(4),
  },
}); 